# Spring Boot configuration
spring:
  profiles:
    active: dev
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/micro_party_quiz_db
    username: micro_party_quiz_user
    password: 111
    max-active: 40
    tomcat:
      logAbandoned: true

  # JPA properties
  jpa:
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
        generate_statistics: false
        ddl-auto: none
        query:
          startup_check: false
        validator:
          apply_to_ddl: false
          autoregister_listeners: false
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
# Server configuration
server:
  port: 8087
#  sessionTimeout: 30